### ISSUE TITLE
Please update to uriparser 0.8.5

### ISSUE THREAD

**Issue by hartwork** [lunar-linux/moonbase-other#1039]
Hi!

uriparser 0.8.5 has been released:
https://github.com/uriparser/uriparser/releases

Thanks for updating!

**Comment by Florin65** [comment]
Done. Thank you.
However until such a similar situation is solved you can copy the module to zlocal directory, make the version bump (uodate the sha256 sum too) and do a lin.

**Comment by hartwork** [comment]
That was quick, thank you!
