### ISSUE TITLE
llvm CMake Error 

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-other#1048]
`-- Up-to-date: /usr/lib/libclangDaemon.so
-- Installing: /usr/bin/clangd
-- Installing: /usr/lib/libclangIncludeFixer.so.6.0.0
-- Up-to-date: /usr/lib/libclangIncludeFixer.so.6
-- Up-to-date: /usr/lib/libclangIncludeFixer.so
-- Installing: /usr/lib/libclangIncludeFixerPlugin.so.6.0.0
-- Up-to-date: /usr/lib/libclangIncludeFixerPlugin.so.6
-- Up-to-date: /usr/lib/libclangIncludeFixerPlugin.so
-- Installing: /usr/bin/clang-include-fixer
-- Up-to-date: /usr/share/clang/clang-include-fixer.el
-- Up-to-date: /usr/share/clang/clang-include-fixer.py
-- Installing: /usr/lib/libfindAllSymbols.so.6.0.0
-- Up-to-date: /usr/lib/libfindAllSymbols.so.6
-- Up-to-date: /usr/lib/libfindAllSymbols.so
-- Installing: /usr/bin/find-all-symbols
-- Up-to-date: /usr/share/clang/run-find-all-symbols.py
CMake Error at tools/clang/tools/extra/docs/cmake_install.cmake:41 (file):
  file INSTALL cannot find
  "/usr/src/llvm-6.0.0.src/llvm-oosb/tools/clang/tools/extra/docs/doxygen/html".
Call Stack (most recent call first):
  tools/clang/tools/extra/cmake_install.cmake:56 (include)
  tools/clang/tools/cmake_install.cmake:59 (include)
  tools/clang/cmake_install.cmake:60 (include)
  tools/cmake_install.cmake:48 (include)
  cmake_install.cmake:65 (include)

make: *** [Makefile:140：install]`

**Comment by stumbles** [comment]
There is a commit to deal with this by disabling the doxygen stuff all together. Give the moonbase 15 minutes or so for an update.

**Comment by Florin65** [comment]
Commited.
