### ISSUE TITLE
ffmpeg building problem

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-other#1087]
`Checking dependencies for ffmpeg 
Building ffmpeg version 4.0
patching file libavformat/tls_openssl.c
GnuTLS and OpenSSL must not be enabled at the same time.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "ffbuild/config.log" produced by configure as this will help
solve the problem.
Creating /var/log/lunar/compile/ffmpeg-4.0.xz 
! Problem detected during BUILD`

@Florin65

**Comment by Florin65** [comment]
At lin time the optional depends for openssl and gnutls are displaying that both options should not be selected. More than that, the gnutls option have default value 'n'. So, please not select it if openssl optional depend is selected (it is at default).
