### ISSUE TITLE
go:The server could not be connected during installation.

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-other#1124]
Due to the existence of GFW, Chinese users cannot directly connect to Google's servers, resulting in the following prompts during the installation of go:

Checking dependencies for go 
Building go version 1.10.3
Building Go cmd/dist using /usr/lib/go.
Building Go toolchain1 using /usr/lib/go.
Building Go bootstrap cmd/go (go_bootstrap) using Go toolchain1.
Building Go toolchain2 using go_bootstrap and Go toolchain1.
Building Go toolchain3 using go_bootstrap and Go toolchain2.
Building packages and commands for linux/amd64.
---
Installed Go for linux/amd64 in /usr/src/go-go1.10.3
Installed commands in /usr/src/go-go1.10.3/bin

The binaries expect /usr/src/go-go1.10.3 to be copied or moved to /usr/lib/go
package golang.org/x/tools/cmd/godoc: unrecognized import path "golang.org/x/tools/cmd/godoc" (https fetch: Get https://golang.org/x/tools/cmd/godoc?go-get=1: dial tcp 173.194.220.141:443: i/o timeout)

Can you have a backup solution that does not connect to Google's servers and connects to an alternate address to complete the installation?

**Comment by Florin65** [comment]
Unfortunately this behaviour is set by upstream devs.
Installing go need access to Google servers.
