### ISSUE TITLE
Please update to uriparser 0.8.6

### ISSUE THREAD

**Issue by hartwork** [lunar-linux/moonbase-other#1140]
Hi!

Just a quick heads up that [uriparser 0.8.6](https://github.com/uriparser/uriparser/releases/tag/uriparser-0.8.6) with bugfixes has been released.

Thanks for updating!

**Comment by stumbles** [comment]
Done with commit 71d386b4c10150a048e498de95dfe2492a6d51b4

**Comment by hartwork** [comment]
Cool, thank you!
