### ISSUE TITLE
colord:some building errors.

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-other#1190]
Program colprof fonud : No
meson.build:168:2:ERROS: Program(s) ['colprof'] not found or not executable.

**Comment by lhw828** [comment]
When Argyll depends on "Y", colord compiles normally.

Does this optional dependency should be changed to a dependency?

**Comment by stumbles** [comment]
Yep, does appear to be a depends.I'll fix that shortly.

**Comment by stumbles** [comment]
Closing with commit c21a6753b4471e6d3a12f7ab7a92fa28a5f78be2.
