### ISSUE TITLE
libjpeg-turbo:some errors

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-other#1191]
Building libjpeg-turbo version 2.0.0
-- The C compiler identification is GNU 8.2.0
-- Check for working C compiler: /var/lib/lunar/compilers/gcc
-- Check for working C compiler: /var/lib/lunar/compilers/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- CMAKE_BUILD_TYPE = RELEASE
-- VERSION = 2.0.0, BUILD = 20181019
-- 64-bit build (x86_64)
-- CMAKE_INSTALL_PREFIX = /usr
-- CMAKE_INSTALL_BINDIR = bin (/usr/bin)
-- CMAKE_INSTALL_DATAROOTDIR = share (/usr/share)
-- CMAKE_INSTALL_DOCDIR = share/doc/libjpeg-turbo (/usr/share/doc/libjpeg-turbo)
-- CMAKE_INSTALL_INCLUDEDIR = include (/usr/include)
-- CMAKE_INSTALL_LIBDIR = lib64 (/usr/lib64)
-- CMAKE_INSTALL_MANDIR = share/man (/usr/share/man)
-- Shared libraries enabled (ENABLE_SHARED = 1)
-- Static libraries disabled (ENABLE_STATIC = 0)
-- 12-bit JPEG support disabled (WITH_12BIT = 0)
-- Arithmetic decoding support enabled (WITH_ARITH_DEC = 1)
-- Arithmetic encoding support enabled (WITH_ARITH_ENC = 1)
-- TurboJPEG API library enabled (WITH_TURBOJPEG = 1)
-- TurboJPEG Java wrapper enabled (WITH_JAVA = 1)
-- Emulating libjpeg API/ABI v8.0 (WITH_JPEG7 = 0, WITH_JPEG8 = 1)
-- libjpeg API shared library version = 8.2.2
-- Compiler flags = -O2 -march=x86-64 -pipe -O3 -DNDEBUG
-- Linker flags = -s 
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of size_t
-- Check size of size_t - done
-- Check size of unsigned long
-- Check size of unsigned long - done
-- Performing Test HAVE_BUILTIN_CTZL
-- Performing Test HAVE_BUILTIN_CTZL - Success
-- Looking for include file locale.h
-- Looking for include file locale.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for memset
-- Looking for memset - found
-- Looking for memcpy
-- Looking for memcpy - found
-- Check size of unsigned char
-- Check size of unsigned char - done
-- Check size of unsigned short
-- Check size of unsigned short - done
-- Performing Test INCOMPLETE_TYPES
-- Performing Test INCOMPLETE_TYPES - Success
-- Compiler supports pointers to undefined structures.
-- Performing Test RIGHT_SHIFT_IS_UNSIGNED
-- Performing Test RIGHT_SHIFT_IS_UNSIGNED - Failed
-- Performing Test __CHAR_UNSIGNED__
-- Performing Test __CHAR_UNSIGNED__ - Failed
-- Performing Test INLINE_WORKS
-- Performing Test INLINE_WORKS - Success
-- INLINE = __inline__ __attribute__((always_inline)) (FORCE_INLINE = 1)
-- Performing Test HAVE_VERSION_SCRIPT
-- Performing Test HAVE_VERSION_SCRIPT - Success
-- Linker supports GNU-style version scripts
-- CMAKE_EXECUTABLE_SUFFIX = 
-- The ASM_NASM compiler identification is NASM
-- Found assembler: /usr/bin/nasm
-- CMAKE_ASM_NASM_COMPILER = /usr/bin/nasm
-- CMAKE_ASM_NASM_OBJECT_FORMAT = elf64
-- CMAKE_ASM_NASM_FLAGS =  -DELF -D__x86_64__ -DPIC 
-- SIMD extensions: x86_64 (WITH_SIMD = 1)
-- Found Java: /usr/bin/java (found version "10.0.2") 
CMake Error at /usr/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find JNI (missing: JAVA_AWT_LIBRARY JAVA_INCLUDE_PATH
  JAVA_INCLUDE_PATH2 JAVA_AWT_INCLUDE_PATH)
Call Stack (most recent call first):
  /usr/share/cmake-3.12/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.12/Modules/FindJNI.cmake:356 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  java/CMakeLists.txt:2 (find_package)

-- Configuring incomplete, errors occurred!
See also "/usr/src/libjpeg-turbo-2.0.0/libjpeg-turbo-oosb/CMakeFiles/CMakeOutput.log".
See also "/usr/src/libjpeg-turbo-2.0.0/libjpeg-turbo-oosb/CMakeFiles/CMakeError.log".

Creating /var/log/lunar/compile/libjpeg-turbo-2.0.0.xz 
! Problem detected during BUILD

**Comment by v4hn** [comment]
Looks like java support is broken at the moment.
Disabling the java opt-dep should work for everything you probably need.

**Comment by lhw828** [comment]
@v4hn You are right~

Thank you~
