### ISSUE TITLE
Please update uriparser to 0.9.0, includes security fixes

### ISSUE THREAD

**Issue by hartwork** [lunar-linux/moonbase-other#1197]
Hi!

Just a quick heads up that [uriparser 0.9.0](https://github.com/uriparser/uriparser/releases/tag/uriparser-0.9.0) with security fixes has been released.

Thanks for updating!

**Comment by stumbles** [comment]
Done, commit 885dc2be7bc5def661a816f23e9d4fbb864ad67d

**Comment by hartwork** [comment]
Thank you!
