### ISSUE TITLE
Add optional mpv build config

### ISSUE THREAD

**Issue by OpenSourceAnarchist** [lunar-linux/moonbase-other#1248]
I'd like to use mpv with vapoursynth support (for compatibility with Smooth Video Project). I can manually change the build script but adding in a choice for vapoursynth support (and possibly other configuration options) with mpv would make this much easier and more manageable.

**Comment by OpenSourceAnarchist** [comment]
Ah, I was assuming Lunar already packaged vapoursynth. I can't find the module in any repo, so I'm assuming it hasn't been packaged yet. I have never packaged anything for any distro, and I am not comfortable creating a whole new package for Lunar at this time. Adding a CONFIGURE file would be manageable for me, but not a build script :)

If it does get packaged, I'll gladly modify the mpv module to ask for vapoursynth support.

**Comment by Florin65** [comment]
OK, I'll see what I can do. Today I have improved mpv a bit.

**Comment by Florin65** [comment]
Done. The needed modules were added to the moonbase.
