### ISSUE TITLE
polkit:some errors

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-other#1346]
/usr/include/glib-2.0/gio/gsimpleasyncresult.h:104:21: note: declared here
 void                g_simple_async_result_complete         (GSimpleAsyncResult      *simple);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CXXLD    libpolkit-backend-1.la
  CXXLD    polkitd
/usr/bin/ld: warning: libicui18n.so.63, needed by /usr/lib/libmozjs-60.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libicuuc.so.63, needed by /usr/lib/libmozjs-60.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libicudata.so.63, needed by /usr/lib/libmozjs-60.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `uloc_toUnicodeLocaleType_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `udat_getCalendar_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ucal_getAttribute_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `u_strToLower_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `unumsys_getName_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `unum_setTextAttribute_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `unum_setAttribute_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ucol_getKeywordValuesForLocale_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `udat_format_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `uplrules_openForType_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ucol_strcoll_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `udatpg_getBestPattern_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `unumsys_open_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ucol_countAvailable_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `udat_getAvailable_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `udat_formatForFields_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `uplrules_selectWithFormat_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ureldatefmt_formatNumeric_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `unorm2_spanQuickCheckYes_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `uplrules_getKeywords_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ucol_open_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ucal_setGregorianChange_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `uloc_countAvailable_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ucal_getType_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `udat_getSymbols_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ucal_getCanonicalTimeZoneID_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `udatpg_close_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ureldatefmt_open_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `unorm2_getNFKDInstance_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `uloc_getAvailable_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `udat_countAvailable_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ucal_get_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `unum_countAvailable_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `unorm2_getNFKCInstance_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `unorm2_normalizeSecondAndAppend_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `unorm2_getNFDInstance_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ucal_openTimeZones_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `u_setMemoryFunctions_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ucol_setAttribute_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ucol_close_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ucal_getDefaultTimeZone_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `udatpg_getAppendItemName_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ucal_close_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ucal_getDayOfWeekType_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ufieldpositer_open_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `udat_open_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `udat_close_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ucol_getAvailable_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `unum_getAvailable_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `uenum_next_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `unum_close_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `u_init_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ucal_getKeywordValuesForLocale_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `uenum_close_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `u_hasBinaryProperty_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ureldatefmt_close_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `uloc_isRightToLeft_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `uenum_count_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `uplrules_close_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `u_cleanup_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ufieldpositer_next_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ucol_openAvailableLocales_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `unum_formatDoubleForFields_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `udatpg_open_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ucol_getAttribute_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `unorm2_getNFCInstance_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `udat_toPattern_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `u_strToUpper_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ufieldpositer_close_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ucal_open_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `unum_open_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `ureldatefmt_format_63'
/usr/bin/ld: /usr/lib/libmozjs-60.so: undefined reference to `unumsys_close_63'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:658: polkitd] Error 1
make[4]: Leaving directory '/usr/src/polkit-0.116/src/polkitbackend'
make[3]: *** [Makefile:559: all] Error 2
make[3]: Leaving directory '/usr/src/polkit-0.116/src/polkitbackend'
make[2]: *** [Makefile:437: all-recursive] Error 1
make[2]: Leaving directory '/usr/src/polkit-0.116/src'
make[1]: *** [Makefile:497: all-recursive] Error 1
make[1]: Leaving directory '/usr/src/polkit-0.116'
make: *** [Makefile:429: all] Error 2
Creating /var/log/lunar/compile/polkit-0.116.xz

**Comment by florin65** [comment]
Do a 'lin -rc mozjs' first and after a 'lin -rc polkit'
