### ISSUE TITLE
Need some Chinese input software.

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-other#1410]
Some Chinese users in order to input Chinese,we need some Chinese input software.
Do you have a moment to help us add some softwate to moonbase?

https://www.archlinux.org/packages/community/x86_64/fcitx/
https://www.archlinux.org/packages/community/x86_64/fcitx-qt5/
https://www.archlinux.org/packages/community/x86_64/fcitx-rime/
https://www.archlinux.org/packages/community/x86_64/fcitx-sunpinyin/
https://www.archlinux.org/packages/community/x86_64/kcm-fcitx/
https://www.archlinux.org/packages/community/x86_64/fcitx-googlepinyin/
https://www.archlinux.org/packages/community/x86_64/fcitx-libpinyin/
https://www.archlinux.org/packages/community/x86_64/fcitx-cloudpinyin/
https://www.archlinux.org/packages/community/x86_64/fcitx-gtk3/
https://www.archlinux.org/packages/community/x86_64/fcitx-gtk2/

https://www.archlinux.org/packages/community/x86_64/fcitx5/
https://www.archlinux.org/packages/community/x86_64/fcitx5-chinese-addons/
https://www.archlinux.org/packages/community/x86_64/fcitx5-qt/
https://www.archlinux.org/packages/community/x86_64/fcitx5-gtk/

https://www.archlinux.org/packages/?sort=&q=fcitx&maintainer=&flagged=

This looks more like my personal wish list.
@florin65 Please help me when you have any available time.
Thanks a lot!

**Comment by stumbles** [comment]
After 3 years, closing.
