### ISSUE TITLE
ruby:some install errors

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-other#1428]
100% [1141/1141]  win32/README.win32

Generating RI format into /usr/src/ruby-2.7.1/.ext/rdoc...

  Files:       1141

  Classes:     1614 ( 758 undocumented)
  Modules:      327 ( 134 undocumented)
  Constants:   2435 ( 726 undocumented)
  Attributes:  1488 ( 559 undocumented)
  Methods:    13019 (3991 undocumented)

  Total:      18883 (6168 undocumented)
   67.34% documented

  Elapsed: 87.4s

./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems -r./x86_64-linux-fake ./tool/rbinstall.rb --make="/usr/bin/make" --dest-dir="" --extout=".ext" --mflags="-j5 --jobserver-auth=4,5" --make-flags=" -j5 --jobserver-auth=4,5" --data-mode=0644 --prog-mode=0755 --installed-list .installed.list --mantype="doc" --rdoc-output=".ext/rdoc" --html-output=".ext/html"
installing binary commands:         /usr/bin
/usr/src/ruby-2.7.1/lib/fileutils.rb:1414:in `initialize': Is a directory @ rb_sysopen - /usr/bin/ruby (Errno::EISDIR)
	from /usr/src/ruby-2.7.1/lib/fileutils.rb:1414:in `open'
	from /usr/src/ruby-2.7.1/lib/fileutils.rb:1414:in `block in copy_file'
	from /usr/src/ruby-2.7.1/lib/fileutils.rb:1413:in `open'
	from /usr/src/ruby-2.7.1/lib/fileutils.rb:1413:in `copy_file'
	from /usr/src/ruby-2.7.1/lib/fileutils.rb:511:in `copy_file'
	from /usr/src/ruby-2.7.1/lib/fileutils.rb:880:in `block in install'
	from /usr/src/ruby-2.7.1/lib/fileutils.rb:1588:in `block in fu_each_src_dest'
	from /usr/src/ruby-2.7.1/lib/fileutils.rb:1602:in `fu_each_src_dest0'
	from /usr/src/ruby-2.7.1/lib/fileutils.rb:1586:in `fu_each_src_dest'
	from /usr/src/ruby-2.7.1/lib/fileutils.rb:876:in `install'
	from ./tool/rbinstall.rb:174:in `install'
	from ./tool/rbinstall.rb:359:in `block in <main>'
	from ./tool/rbinstall.rb:950:in `block in <main>'
	from ./tool/rbinstall.rb:947:in `each'
	from ./tool/rbinstall.rb:947:in `<main>'
make: *** [uncommon.mk:373:do-install-all] Error 1

**Comment by lhw828** [comment]
99% [1137/1141]  vm_method.c
 99% [1138/1141]  vm_trace.c
 99% [1139/1141]  vsnprintf.c
 99% [1140/1141]  warning.rb
100% [1141/1141]  win32/README.win32

Generating RI format into /usr/src/ruby-2.7.1/.ext/rdoc...


  Files:       1141

  Classes:     1614 ( 758 undocumented)
  Modules:      327 ( 134 undocumented)
  Constants:   2435 ( 726 undocumented)
  Attributes:  1488 ( 559 undocumented)
  Methods:    13019 (3991 undocumented)

  Total:      18883 (6168 undocumented)
   67.34% documented

  Elapsed: 338.1s

./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems -r./x86_64-linux-fake ./tool/rbinstall.rb --make="/usr/bin/make" --dest-dir="" --extout=".ext" --mflags="-j5 --jobserver-auth=4,5" --make-flags=" -j5 --jobserver-auth=4,5" --data-mode=0644 --prog-mode=0755 --installed-list .installed.list --mantype="doc" --rdoc-output=".ext/rdoc" --html-output=".ext/html"
installing binary commands:         /usr/bin
/usr/src/ruby-2.7.1/lib/fileutils.rb:1414:in `initialize': Is a directory @ rb_sysopen - /usr/bin/ruby (Errno::EISDIR)
        from /usr/src/ruby-2.7.1/lib/fileutils.rb:1414:in `open'
        from /usr/src/ruby-2.7.1/lib/fileutils.rb:1414:in `block in copy_file'
        from /usr/src/ruby-2.7.1/lib/fileutils.rb:1413:in `open'
        from /usr/src/ruby-2.7.1/lib/fileutils.rb:1413:in `copy_file'
        from /usr/src/ruby-2.7.1/lib/fileutils.rb:511:in `copy_file'
        from /usr/src/ruby-2.7.1/lib/fileutils.rb:880:in `block in install'
        from /usr/src/ruby-2.7.1/lib/fileutils.rb:1588:in `block in fu_each_src_dest'
        from /usr/src/ruby-2.7.1/lib/fileutils.rb:1602:in `fu_each_src_dest0'
        from /usr/src/ruby-2.7.1/lib/fileutils.rb:1586:in `fu_each_src_dest'
        from /usr/src/ruby-2.7.1/lib/fileutils.rb:876:in `install'
        from ./tool/rbinstall.rb:174:in `install'
        from ./tool/rbinstall.rb:359:in `block in <main>'
        from ./tool/rbinstall.rb:950:in `block in <main>'
        from ./tool/rbinstall.rb:947:in `each'
        from ./tool/rbinstall.rb:947:in `<main>'
make: *** [uncommon.mk:373: do-install-all] Error 1
Creating /var/log/lunar/compile/ruby-2.7.1.xz 
! Problem detected during BUILD

**Comment by v4hn** [comment]
On Mon, Apr 20, 2020 at 09:22:24PM -0700, lhw828 wrote:
> /usr/src/ruby-2.7.1/lib/fileutils.rb:1414:in `initialize': Is a directory @ rb_sysopen - /usr/bin/ruby (Errno::EISDIR)

Did you manage (somehow) to have a *folder* with the path `/usr/bin/ruby` on your system?
If so, guess you should just remove it and retry...

**Comment by lhw828** [comment]
It's amazing it was fixed.
