### ISSUE TITLE
Chromium-arch:can not to use

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-other#1430]
#:chromium 
/usr/lib/chromium/chromium: error while loading shared libraries: libicui18n.so.65: cannot open shared object file: No such file or directory

**Comment by v4hn** [comment]
Hm, so they rely on an older version of icu installed on the system.

Of course we could try to package the "older" version of icu too, though I'm not too eager to do so.
If you enabled the new `KEEP_OBSOLETE_LIBS` option in `lunar`, you could `lin -w 65-1 icu4c; lin icu4c` to build/install the old version again. As the older library is still required by `chromium-arch` the feature will keep it around in `/usr/lib/lunar/OBSOLETE/`.

Alternatively you could either (1) stay with the old version of icu4c for now, (2) use the `chromium` module (and fix it if it should not compile), (3) try `ln -s /usr/lib/libicui18n.so.66 libicui18n.so.65`, run and hide behind something that can withstand an impact and hope the library did not break an interface required by `chromium-arch`, or (4) try to push upstream to provide binary builds linking the new version of icu4c.

**Comment by lhw828** [comment]
The soft link method, which I tried before, proved infeasible.
bash-5.0# chromium 
/usr/lib/chromium/chromium: symbol lookup error: /usr/lib/chromium/chromium: undefined symbol: _ZN6icu_6513BreakIterator23createCharacterInstanceERKNS_6LocaleER10UErrorCode

**Comment by v4hn** [comment]
Too bad, but to be expected. After all they bumped SONAME and apparently change ABI a lot...
