### ISSUE TITLE
assimp:need libicuuc.so.67

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-other#1530]
Checking dependencies for assimp
Building assimp version 5.0.1
cmake: error while loading shared libraries: libicuuc.so.67: cannot open shared object file: No such file or directory
Creating /var/log/lunar/compile/assimp-5.0.1.xz

**Comment by stumbles** [comment]
The problem is the icu version bump florin did. You need to run "lunar fix". Your real issue is with cmake.

**Comment by esselfe** [comment]
Yeah, you can also just run ```lin -rc cmake```
