### ISSUE TITLE
convert from ImageMagick is broken

### ISSUE THREAD

**Issue by esselfe** [lunar-linux/moonbase-other#1591]
Convert is broken since --with-modules was added, see comments in https://github.com/lunar-linux/moonbase-other/commit/ffcfa0789299fb11e8341ce5a96392254ff76a49#diff-9b5c7d4ac56f11bbbe2a041cb3a1a51f5f5d28efa192d920d641afd1783b24f5

**Comment by v4hn** [comment]
Should be fixed by d647ce83dfa04c2d53b374095d132ffca6216318
