### ISSUE TITLE
mozjs78: The 0002-Fixes-for-Python-3.10.patch has some problems

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-other#1641]
Building mozjs78 version 78.15.0
/var/lib/lunar/plugins/build-zpatches.plugin: line 20: cd: firefox-78.15.0: No such file or directory
patching file build/moz.configure/lto-pgo.configure
patching file config/makefiles/rust.mk
patching file python/mach/mach/config.py
patching file python/mach/mach/decorators.py
patching file python/mach/mach/main.py
patching file python/mozbuild/mozbuild/backend/configenvironment.py
patching file python/mozbuild/mozbuild/makeutil.py
patching file python/mozbuild/mozbuild/util.py
patching file taskcluster/taskgraph/util/schema.py
patching file testing/mozbase/manifestparser/manifestparser/filters.py
patching file third_party/python/gyp/pylib/gyp/common.py
patching file third_party/python/requirements.in
patching file third_party/python/requirements.txt
patching file third_party/python/voluptuous/voluptuous-0.12.1.dist-info/COPYING (copied from third_party/python/voluptuous/COPYING)
patching file third_party/python/voluptuous/voluptuous-0.12.1.dist-info/METADATA (renamed from third_party/python/voluptuous/README.md)
The next patch would create the file third_party/python/voluptuous/voluptuous-0.12.1.dist-info/RECORD,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file third_party/python/voluptuous/voluptuous-0.12.1.dist-info/WHEEL,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
patching file third_party/python/voluptuous/voluptuous-0.12.1.dist-info/top_level.txt (already renamed from third_party/python/psutil-cp27-none-win_amd64/psutil-5.7.0.dist-info/top_level.txt)
patching file third_party/python/voluptuous/voluptuous/__init__.py
patching file third_party/python/voluptuous/voluptuous/error.py
patching file third_party/python/voluptuous/voluptuous/schema_builder.py
patching file third_party/python/voluptuous/voluptuous/util.py
patching file third_party/python/voluptuous/voluptuous/validators.py
can't find file to patch at input line 40
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|From 0000000000000000000000000000000000000000 Mon Sep 17 00:00:00 2001
|From: "Jan Alexander Steffens (heftig)" <jan.steffens@gmail.com>
|Date: Tue, 11 Jan 2022 19:26:43 +0100
|Subject: [PATCH] Fixes for Python 3.10
|
|Bug 1719144 cherry-picked from Firefox Nightly.
|---
| python/mach/mach/config.py                    |   5 +-
| python/mach/mach/decorators.py                |   3 +-
| python/mach/mach/main.py                      |   2 +-
| .../mozbuild/backend/configenvironment.py     |   3 +-
| python/mozbuild/mozbuild/makeutil.py          |   2 +-
| python/mozbuild/mozbuild/util.py              |   3 +-
| taskcluster/taskgraph/util/schema.py          |   3 +-
| .../manifestparser/manifestparser/filters.py  |   3 +-
| third_party/python/gyp/pylib/gyp/common.py    |   3 +-
| third_party/python/requirements.in            |   2 +-
| third_party/python/requirements.txt           |   6 +-
| .../{ => voluptuous-0.12.1.dist-info}/COPYING |   0
| .../METADATA}                                 | 114 +++++++---
| .../voluptuous-0.12.1.dist-info/RECORD        |  11 +
| .../voluptuous-0.12.1.dist-info/WHEEL         |  11 +
| .../top_level.txt                             |   0
| .../python/voluptuous/voluptuous/__init__.py  |   2 +-
| .../python/voluptuous/voluptuous/error.py     |   4 +-
| .../voluptuous/voluptuous/schema_builder.py   |  25 ++-
| .../python/voluptuous/voluptuous/util.py      |  18 +-
| .../voluptuous/voluptuous/validators.py       | 198 ++++++++++++------
| 21 files changed, 300 insertions(+), 118 deletions(-)
| copy third_party/python/voluptuous/{ => voluptuous-0.12.1.dist-info}/COPYING (100%)
| rename third_party/python/voluptuous/{README.md => voluptuous-0.12.1.dist-info/METADATA} (83%)
| create mode 100644 third_party/python/voluptuous/voluptuous-0.12.1.dist-info/RECORD
| create mode 100644 third_party/python/voluptuous/voluptuous-0.12.1.dist-info/WHEEL
| rename third_party/python/{psutil-cp27-none-win_amd64/psutil-5.7.0.dist-info => voluptuous/voluptuous-0.12.1.dist-info}/top_level.txt (100%)
|
|diff --git a/python/mach/mach/config.py b/python/mach/mach/config.py
|index 7210eca82308..6605e381b310 100644
|--- a/python/mach/mach/config.py
|+++ b/python/mach/mach/config.py
--------------------------
No file to patch.  Skipping patch.
3 out of 3 hunks ignored
can't find file to patch at input line 70
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/python/mach/mach/decorators.py b/python/mach/mach/decorators.py
|index 27f7f34a6ddc..8b1a49c76dc2 100644
|--- a/python/mach/mach/decorators.py
|+++ b/python/mach/mach/decorators.py
--------------------------
No file to patch.  Skipping patch.
2 out of 2 hunks ignored
can't find file to patch at input line 91
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/python/mach/mach/main.py b/python/mach/mach/main.py
|index a7311806d0a4..0f2c6a16d9d2 100644
|--- a/python/mach/mach/main.py
|+++ b/python/mach/mach/main.py
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 104
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/python/mozbuild/mozbuild/backend/configenvironment.py b/python/mozbuild/mozbuild/backend/configenvironment.py
|index 20d1a9fa69da..898cabb73b0b 100644
|--- a/python/mozbuild/mozbuild/backend/configenvironment.py
|+++ b/python/mozbuild/mozbuild/backend/configenvironment.py
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 118
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/python/mozbuild/mozbuild/makeutil.py b/python/mozbuild/mozbuild/makeutil.py
|index 4da1a3b268e5..4ce56848cd6c 100644
|--- a/python/mozbuild/mozbuild/makeutil.py
|+++ b/python/mozbuild/mozbuild/makeutil.py
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 131
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/python/mozbuild/mozbuild/util.py b/python/mozbuild/mozbuild/util.py
|index 044cf645c1f1..ed30088c0059 100644
|--- a/python/mozbuild/mozbuild/util.py
|+++ b/python/mozbuild/mozbuild/util.py
--------------------------
No file to patch.  Skipping patch.
2 out of 2 hunks ignored
can't find file to patch at input line 152
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/taskcluster/taskgraph/util/schema.py b/taskcluster/taskgraph/util/schema.py
|index 0b15d3d5fd6f..29e36793f336 100644
|--- a/taskcluster/taskgraph/util/schema.py
|+++ b/taskcluster/taskgraph/util/schema.py
--------------------------
No file to patch.  Skipping patch.
2 out of 2 hunks ignored
can't find file to patch at input line 173
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/testing/mozbase/manifestparser/manifestparser/filters.py b/testing/mozbase/manifestparser/manifestparser/filters.py
|index 287ee033b222..b1d6080031f6 100644
|--- a/testing/mozbase/manifestparser/manifestparser/filters.py
|+++ b/testing/mozbase/manifestparser/manifestparser/filters.py
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 187
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/third_party/python/gyp/pylib/gyp/common.py b/third_party/python/gyp/pylib/gyp/common.py
|index b268d229a483..2195e1e458e3 100644
|--- a/third_party/python/gyp/pylib/gyp/common.py
|+++ b/third_party/python/gyp/pylib/gyp/common.py
--------------------------
No file to patch.  Skipping patch.
2 out of 2 hunks ignored
can't find file to patch at input line 208
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/third_party/python/requirements.in b/third_party/python/requirements.in
|index b65c92e30c09..1127ab280c84 100644
|--- a/third_party/python/requirements.in
|+++ b/third_party/python/requirements.in
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 218
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/third_party/python/requirements.txt b/third_party/python/requirements.txt
|index fd0b6cb1a181..5742c9cdb771 100644
|--- a/third_party/python/requirements.txt
|+++ b/third_party/python/requirements.txt
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
Cannot copy file without two valid file names
Cannot rename file without two valid file names
4 out of 4 hunks ignored
The next patch would create the file b/third_party/python/voluptuous/voluptuous-0.12.1.dist-info/RECORD,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
The next patch would create the file b/third_party/python/voluptuous/voluptuous-0.12.1.dist-info/WHEEL,
which already exists!  Skipping patch.
1 out of 1 hunk ignored
Cannot rename file without two valid file names
can't find file to patch at input line 432
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/third_party/python/voluptuous/voluptuous/__init__.py b/third_party/python/voluptuous/voluptuous/__init__.py
|index 10236d5a6670..4d09fe670fd4 100644
|--- a/third_party/python/voluptuous/voluptuous/__init__.py
|+++ b/third_party/python/voluptuous/voluptuous/__init__.py
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 443
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/third_party/python/voluptuous/voluptuous/error.py b/third_party/python/voluptuous/voluptuous/error.py
|index 86c4e0a35933..97f37d2c7c4b 100644
|--- a/third_party/python/voluptuous/voluptuous/error.py
|+++ b/third_party/python/voluptuous/voluptuous/error.py
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 461
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/third_party/python/voluptuous/voluptuous/schema_builder.py b/third_party/python/voluptuous/voluptuous/schema_builder.py
|index 8d7a81a3e3e5..df19c8da2ddf 100644
|--- a/third_party/python/voluptuous/voluptuous/schema_builder.py
|+++ b/third_party/python/voluptuous/voluptuous/schema_builder.py
--------------------------
No file to patch.  Skipping patch.
7 out of 7 hunks ignored
can't find file to patch at input line 544
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/third_party/python/voluptuous/voluptuous/util.py b/third_party/python/voluptuous/voluptuous/util.py
|index 434c360c7e95..e0ff43f8500a 100644
|--- a/third_party/python/voluptuous/voluptuous/util.py
|+++ b/third_party/python/voluptuous/voluptuous/util.py
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 616
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/third_party/python/voluptuous/voluptuous/validators.py b/third_party/python/voluptuous/voluptuous/validators.py
|index d5e3ed598051..fac9cc7717c0 100644
|--- a/third_party/python/voluptuous/voluptuous/validators.py
|+++ b/third_party/python/voluptuous/voluptuous/validators.py
--------------------------
No file to patch.  Skipping patch.
12 out of 12 hunks ignored
ERROR: Failed to apply 0002-Fixes-for-Python-3.10.patch for mozjs78

**Comment by stumbles** [comment]
Unable to duplicate. They apply fine here:

Building mozjs78 version 78.15.0
+ building "mozjs78" version "78.15.0" in /usr/src/firefox-78.15.0
/var/lib/lunar/plugins/build-zpatches.plugin: line 20: cd: firefox-78.15.0: No such file or directory
+ Applying 0001-Fixes-for-LTO-PGO-support.patch for mozjs78
patching file build/moz.configure/lto-pgo.configure
patching file config/makefiles/rust.mk
+ Applying 0002-Fixes-for-Python-3.10.patch for mozjs78
patching file python/mach/mach/config.py
patching file python/mach/mach/decorators.py
patching file python/mach/mach/main.py
patching file python/mozbuild/mozbuild/backend/configenvironment.py
patching file python/mozbuild/mozbuild/makeutil.py
patching file python/mozbuild/mozbuild/util.py
patching file taskcluster/taskgraph/util/schema.py
patching file testing/mozbase/manifestparser/manifestparser/filters.py
patching file third_party/python/gyp/pylib/gyp/common.py
patching file third_party/python/requirements.in
patching file third_party/python/requirements.txt
patching file third_party/python/voluptuous/voluptuous-0.12.1.dist-info/COPYING (copied from third_party/python/voluptuous/COPYING)
patching file third_party/python/voluptuous/voluptuous-0.12.1.dist-info/METADATA (renamed from third_party/python/voluptuous/README.md)
patching file third_party/python/voluptuous/voluptuous-0.12.1.dist-info/RECORD
patching file third_party/python/voluptuous/voluptuous-0.12.1.dist-info/WHEEL
patching file third_party/python/voluptuous/voluptuous-0.12.1.dist-info/top_level.txt (renamed from third_party/python/psutil-cp27-none-win_amd64/psutil-5.7.0.dist-info/top_level.txt)
patching file third_party/python/voluptuous/voluptuous/__init__.py
patching file third_party/python/voluptuous/voluptuous/error.py
patching file third_party/python/voluptuous/voluptuous/schema_builder.py
patching file third_party/python/voluptuous/voluptuous/util.py
patching file third_party/python/voluptuous/voluptuous/validators.py
+ Applying 0003-Fixes-for-Rust-1.56.patch for mozjs78
patching file .cargo/config.in
patching file Cargo.lock
patching file Cargo.toml
patching file third_party/rust/packed_simd/.cargo-checksum.json
patching file third_party/rust/packed_simd/Cargo.toml
patching file third_party/rust/packed_simd/build.rs
patching file third_party/rust/packed_simd/src/api/shuffle.rs
patching file third_party/rust/packed_simd/src/codegen/llvm.rs
patching file third_party/rust/packed_simd/src/lib.rs
+ CC_EXT="ccache "
+ CXX_EXT="ccache "
+ CC="gcc"
+ CXX="g++"
+ CPP="cpp"
+ CFLAGS=" -O2 -march=native -pipe"
+ CXXFLAGS=" -O2 -march=native -pipe"
+ CPPFLAGS=" -D_FORTIFY_SOURCE=2"
+ LDFLAGS=" -s"
+ MAKES="9"
+ Enabled wrapper script usage
Creating Python 3 environment
created virtual environment CPython3.10.1.final.0-64 in 296ms
