### ISSUE TITLE
assimp:error: 'zlib_filefunc_def' {aka 'struct zlib_filefunc_def_s'} has no member named 'zopendisk_file'

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-other#1651]
Checking dependencies for assimp 
Building assimp version 5.2.2
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /var/lib/lunar/compilers/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /var/lib/lunar/compilers/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Shared libraries enabled
-- Looking for ZLIB...
-- Found PkgConfig: /usr/bin/pkg-config (found version "1.8.0") 
-- Checking for module 'zzip-zlib-config'
--   Package 'zzip-zlib-config', required by 'virtual:world', not found
-- Found ZLIB: optimized;/lib/libz.so;debug;/lib/libz.so
-- Checking for module 'minizip'
--   Found minizip, version 1.2.11
-- Enabled importer formats: AMF 3DS AC ASE ASSBIN B3D BVH COLLADA DXF CSM HMP IRRMESH IQM IRR LWO LWS M3D MD2 MD3 MD5 MDC MDL NFF NDO OFF OBJ OGRE OPENGEX PLY MS3D COB BLEND IFC XGL FBX Q3D Q3BSP RAW SIB SMD STL TERRAGEN 3D X X3D GLTF 3MF MMD
-- Disabled importer formats:
-- Enabled exporter formats: OBJ OPENGEX PLY 3DS ASSBIN ASSXML M3D COLLADA FBX STL X X3D GLTF 3MF PBRT ASSJSON STEP
-- Disabled exporter formats:
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    BUILD_TESTING
    SYSCONF_INSTALL_DIR

-- Build files have been written to: /usr/src/assimp-5.2.2/assimp-oosb
[  0%] Building CXX object code/CMakeFiles/assimp.dir/Common/Assimp.cpp.o
[  1%] Building CXX object code/CMakeFiles/assimp.dir/Common/Compression.cpp.o
[  1%] Building CXX object code/CMakeFiles/assimp.dir/CApi/CInterfaceIOWrapper.cpp.o
[  1%] Building CXX object code/CMakeFiles/assimp.dir/Common/BaseImporter.cpp.o
[  2%] Building CXX object code/CMakeFiles/assimp.dir/Common/BaseProcess.cpp.o
[  2%] Building CXX object code/CMakeFiles/assimp.dir/Common/PostStepRegistry.cpp.o
[  3%] Building CXX object code/CMakeFiles/assimp.dir/Common/DefaultIOStream.cpp.o
[  3%] Building CXX object code/CMakeFiles/assimp.dir/Common/ImporterRegistry.cpp.o
[  3%] Building CXX object code/CMakeFiles/assimp.dir/Common/IOSystem.cpp.o
[  4%] Building CXX object code/CMakeFiles/assimp.dir/Common/DefaultIOSystem.cpp.o
[  4%] Building CXX object code/CMakeFiles/assimp.dir/Common/ZipArchiveIOSystem.cpp.o
[  5%] Building CXX object code/CMakeFiles/assimp.dir/Common/Importer.cpp.o
[  5%] Building CXX object code/CMakeFiles/assimp.dir/Common/SGSpatialSort.cpp.o
[  5%] Building CXX object code/CMakeFiles/assimp.dir/Common/VertexTriangleAdjacency.cpp.o
[  6%] Building CXX object code/CMakeFiles/assimp.dir/Common/SpatialSort.cpp.o
[  6%] Building CXX object code/CMakeFiles/assimp.dir/Common/SceneCombiner.cpp.o
[  7%] Building CXX object code/CMakeFiles/assimp.dir/Common/ScenePreprocessor.cpp.o
[  8%] Building CXX object code/CMakeFiles/assimp.dir/Common/StandardShapes.cpp.o
[  8%] Building CXX object code/CMakeFiles/assimp.dir/Common/SkeletonMeshBuilder.cpp.o
[  8%] Building CXX object code/CMakeFiles/assimp.dir/Common/TargetAnimation.cpp.o
[  8%] Building CXX object code/CMakeFiles/assimp.dir/Common/RemoveComments.cpp.o
[  9%] Building CXX object code/CMakeFiles/assimp.dir/Common/Subdivision.cpp.o
[  9%] Building CXX object code/CMakeFiles/assimp.dir/Common/scene.cpp.o
[ 10%] Building CXX object code/CMakeFiles/assimp.dir/Common/Bitmap.cpp.o
[ 10%] Building CXX object code/CMakeFiles/assimp.dir/Common/Version.cpp.o
[ 10%] Building CXX object code/CMakeFiles/assimp.dir/Common/CreateAnimMesh.cpp.o
[ 11%] Building CXX object code/CMakeFiles/assimp.dir/Common/simd.cpp.o
[ 11%] Building CXX object code/CMakeFiles/assimp.dir/Common/material.cpp.o
[ 12%] Building CXX object code/CMakeFiles/assimp.dir/Common/AssertHandler.cpp.o
/usr/src/assimp-5.2.2/code/Common/ZipArchiveIOSystem.cpp: In static member function 'static zlib_filefunc_def Assimp::IOSystem2Unzip::get(Assimp::IOSystem*)':
/usr/src/assimp-5.2.2/code/Common/ZipArchiveIOSystem.cpp:199:13: error: 'zlib_filefunc_def' {aka 'struct zlib_filefunc_def_s'} has no member named 'zopendisk_file'; did you mean 'zopen_file'?
  199 |     mapping.zopendisk_file = (opendisk_file_func)opendisk;
      |             ^~~~~~~~~~~~~~
      |             zopen_file
/usr/src/assimp-5.2.2/code/Common/ZipArchiveIOSystem.cpp:199:31: error: 'opendisk_file_func' was not declared in this scope; did you mean 'open64_file_func'?
  199 |     mapping.zopendisk_file = (opendisk_file_func)opendisk;
      |                               ^~~~~~~~~~~~~~~~~~
      |                               open64_file_func
make[2]: *** [code/CMakeFiles/assimp.dir/build.make:216: code/CMakeFiles/assimp.dir/Common/ZipArchiveIOSystem.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:143: code/CMakeFiles/assimp.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

Creating /var/log/lunar/compile/assimp-5.2.2.xz 
! Problem detected during BUILD

**When i re-lin zlib,show like this:**

[ 13%] Building CXX object code/CMakeFiles/assimp.dir/Common/DefaultLogger.cpp.o
[ 13%] Building CXX object code/CMakeFiles/assimp.dir/Common/Exporter.cpp.o
[ 14%] Building CXX object code/CMakeFiles/assimp.dir/CApi/AssimpCExport.cpp.o
/usr/src/assimp-5.2.2/code/Common/ZipArchiveIOSystem.cpp: In static member function 'static zlib_filefunc_def Assimp::IOSystem2Unzip::get(Assimp::IOSystem*)':
/usr/src/assimp-5.2.2/code/Common/ZipArchiveIOSystem.cpp:199:13: error: 'zlib_filefunc_def' {aka 'struct zlib_filefunc_def_s'} has no member named 'zopendisk_file'; did you mean 'zopen_file'?
  199 |     mapping.zopendisk_file = (opendisk_file_func)opendisk;
      |             ^~~~~~~~~~~~~~
      |             zopen_file
/usr/src/assimp-5.2.2/code/Common/ZipArchiveIOSystem.cpp:199:31: error: 'opendisk_file_func' was not declared in this scope; did you mean 'open64_file_func'?
  199 |     mapping.zopendisk_file = (opendisk_file_func)opendisk;
      |                               ^~~~~~~~~~~~~~~~~~
      |                               open64_file_func
make[2]: *** [code/CMakeFiles/assimp.dir/build.make:216: code/CMakeFiles/assimp.dir/Common/ZipArchiveIOSystem.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:143: code/CMakeFiles/assimp.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Then i re-lin minizip,The display is as follows:**

[ 14%] Building CXX object code/CMakeFiles/assimp.dir/PostProcessing/CalcTangentsProcess.cpp.o
[ 15%] Building CXX object code/CMakeFiles/assimp.dir/PostProcessing/ComputeUVMappingProcess.cpp.o
[ 15%] Building CXX object code/CMakeFiles/assimp.dir/PostProcessing/ConvertToLHProcess.cpp.o
[ 16%] Building CXX object code/CMakeFiles/assimp.dir/PostProcessing/EmbedTexturesProcess.cpp.o
/usr/src/assimp-5.2.2/code/Common/ZipArchiveIOSystem.cpp: In static member function 'static zlib_filefunc_def Assimp::IOSystem2Unzip::get(Assimp::IOSystem*)':
/usr/src/assimp-5.2.2/code/Common/ZipArchiveIOSystem.cpp:199:13: error: 'zlib_filefunc_def' {aka 'struct zlib_filefunc_def_s'} has no member named 'zopendisk_file'; did you mean 'zopen_file'?
  199 |     mapping.zopendisk_file = (opendisk_file_func)opendisk;
      |             ^~~~~~~~~~~~~~
      |             zopen_file
/usr/src/assimp-5.2.2/code/Common/ZipArchiveIOSystem.cpp:199:31: error: 'opendisk_file_func' was not declared in this scope; did you mean 'open64_file_func'?
  199 |     mapping.zopendisk_file = (opendisk_file_func)opendisk;
      |                               ^~~~~~~~~~~~~~~~~~
      |                               open64_file_func
make[2]: *** [code/CMakeFiles/assimp.dir/build.make:216: code/CMakeFiles/assimp.dir/Common/ZipArchiveIOSystem.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:143: code/CMakeFiles/assimp.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

Creating /var/log/lunar/compile/assimp-5.2.2.xz

**Comment by lhw828** [comment]
[ 17%] Building CXX object code/CMakeFiles/assimp.dir/PostProcessing/FixNormalsStep.cpp.o
[ 18%] Building CXX object code/CMakeFiles/assimp.dir/PostProcessing/DropFaceNormalsProcess.cpp.o
[ 18%] Building CXX object code/CMakeFiles/assimp.dir/PostProcessing/GenFaceNormalsProcess.cpp.o
[ 18%] Building CXX object code/CMakeFiles/assimp.dir/PostProcessing/GenVertexNormalsProcess.cpp.o
[ 19%] Building CXX object code/CMakeFiles/assimp.dir/PostProcessing/PretransformVertices.cpp.o
/usr/src/assimp-5.2.2/code/Common/ZipArchiveIOSystem.cpp: In static member function 'static zlib_filefunc_def Assimp::IOSystem2Unzip::get(Assimp::IOSystem*)':
/usr/src/assimp-5.2.2/code/Common/ZipArchiveIOSystem.cpp:199:13: error: 'zlib_filefunc_def' {aka 'struct zlib_filefunc_def_s'} has no member named 'zopendisk_file'; did you mean 'zopen_file'?
  199 |     mapping.zopendisk_file = (opendisk_file_func)opendisk;
      |             ^~~~~~~~~~~~~~
      |             zopen_file
/usr/src/assimp-5.2.2/code/Common/ZipArchiveIOSystem.cpp:199:31: error: 'opendisk_file_func' was not declared in this scope; did you mean 'open64_file_func'?
  199 |     mapping.zopendisk_file = (opendisk_file_func)opendisk;
      |                               ^~~~~~~~~~~~~~~~~~
      |                               open64_file_func
make[2]: *** [code/CMakeFiles/assimp.dir/build.make:216: code/CMakeFiles/assimp.dir/Common/ZipArchiveIOSystem.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:143: code/CMakeFiles/assimp.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by stumbles** [comment]
Fixed with commit 685325e0b2fbd4b1872b8053aa03a3e08c161fb1 adding a CONFIGURE to use assimp or system provided zlib. Defaults to assimp provided.
