### ISSUE TITLE
git:WARNING: BUILD does not call prepare_install or installs zero files!

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-other#1838]
Generating catalog po/zh_cn.msg
tclsh po/po2msg.sh --statistics --tcl po/zh_cn.po -l zh_cn -d po/
311 translated messages, 0 fuzzy ones, 0 untranslated ones.
    GEN gitk-wish
311 translated messages, 0 fuzzy ones, 0 untranslated ones.
307 translated messages, 0 fuzzy ones, 0 untranslated ones.
317 translated messages, 0 fuzzy ones, 0 untranslated ones.
317 translated messages, 0 fuzzy ones, 0 untranslated ones.
    SUBDIR templates
    MSGFMT po/build/locale/bg/LC_MESSAGES/git.mo
    MSGFMT po/build/locale/ca/LC_MESSAGES/git.mo
    MSGFMT po/build/locale/de/LC_MESSAGES/git.mo
    MSGFMT po/build/locale/el/LC_MESSAGES/git.mo
msgfmt: error while loading shared libraries: libicuuc.so.70: cannot open shared object file: No such file or directory
    MSGFMT po/build/locale/es/LC_MESSAGES/git.mo
make: *** [Makefile:2743: po/build/locale/bg/LC_MESSAGES/git.mo] Error 127
make: *** Waiting for unfinished jobs....
msgfmt: error while loading shared libraries: libicuuc.so.70: cannot open shared object file: No such file or directory
msgfmt: error while loading shared libraries: libicuuc.so.70: cannot open shared object file: No such file or directory
make: *** [Makefile:2743: po/build/locale/ca/LC_MESSAGES/git.mo] Error 127
make: *** [Makefile:2743: po/build/locale/de/LC_MESSAGES/git.mo] Error 127
msgfmt: error while loading shared libraries: libicuuc.so.70: cannot open shared object file: No such file or directory
make: *** [Makefile:2743: po/build/locale/el/LC_MESSAGES/git.mo] Error 127
msgfmt: error while loading shared libraries: libicuuc.so.70: cannot open shared object file: No such file or directory
make: *** [Makefile:2743: po/build/locale/es/LC_MESSAGES/git.mo] Error 127
    SUBDIR git-gui
    SUBDIR gitk-git
    SUBDIR templates
    MSGFMT po/build/locale/bg/LC_MESSAGES/git.mo
    MSGFMT po/build/locale/ca/LC_MESSAGES/git.mo
    MSGFMT po/build/locale/de/LC_MESSAGES/git.mo
    MSGFMT po/build/locale/el/LC_MESSAGES/git.mo
msgfmt: error while loading shared libraries: libicuuc.so.70: cannot open shared object file: No such file or directory
    MSGFMT po/build/locale/es/LC_MESSAGES/git.mo
msgfmt: error while loading shared libraries: libicuuc.so.70: cannot open shared object file: No such file or directory
make: *** [Makefile:2743: po/build/locale/bg/LC_MESSAGES/git.mo] Error 127
msgfmt: error while loading shared libraries: libicuuc.so.70: cannot open shared object file: No such file or directory
make: *** Waiting for unfinished jobs....
make: *** [Makefile:2743: po/build/locale/el/LC_MESSAGES/git.mo] Error 127
make: *** [Makefile:2743: po/build/locale/ca/LC_MESSAGES/git.mo] Error 127
msgfmt: error while loading shared libraries: libicuuc.so.70: cannot open shared object file: No such file or directory
make: *** [Makefile:2743: po/build/locale/de/LC_MESSAGES/git.mo] Error 127
msgfmt: error while loading shared libraries: libicuuc.so.70: cannot open shared object file: No such file or directory
make: *** [Makefile:2743: po/build/locale/es/LC_MESSAGES/git.mo] Error 127
WARNING: BUILD does not call prepare_install or installs zero files!
Creating /var/log/lunar/compile/git-2.35.3.xz 
Creating /var/log/lunar/install/git-2.35.3
Creating /var/log/lunar/md5sum/git-2.35.3
Creating /var/cache/lunar/git-2.35.3-x86_64-pc-linux-gnu.tar.xz

**Comment by stumbles** [comment]
Again it is related to the icu4c bump. All you can do is lunar fix.
