### ISSUE TITLE
node:Assembler messages

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-other#1859]
Building node version 18.2.0
patching file src/cares_wrap.h
Node.js configure: Found Python 3.10.1...
WARNING: Could not recognize `gas`: as: /lib/libz.so.1: no version information available (required by /usr/lib/libbfd-2.34.so)
GNU assembler version 2.34 (x86_64-pc-linux-gnu) using BFD version (GNU Binutils) 2.34
Assembler messages:
Fatal error: The input '/dev/null' and output '/dev/null' files are the same

ERROR: Did not find a new enough assembler, install one or build with
       --openssl-no-asm.
       Please refer to BUILDING.md
Creating /var/log/lunar/compile/node-18.2.0.xz

**Comment by stumbles** [comment]
Trying recompiling binutils.
