### ISSUE TITLE
fwupd:meson.build:542:4: ERROR: Problem encountered: 

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-other#1863]
Has header "malloc.h" : YES 
Checking for function "malloc_trim" : YES 
Header <cpuid.h> has symbol "__get_cpuid_count" : YES 
Checking for function "getuid" : YES 
Checking for function "realpath" : YES 
Checking for function "memmem" : YES 
Checking for function "sigaction" : YES 
Checking for function "memfd_create" : YES 
Header <locale.h> has symbol "LC_MESSAGES" : YES 
Has header "linux/ipmi.h" : YES 
Header <fcntl.h> has symbol "F_WRLCK" : YES 
Header <fcntl.h> has symbol "F_OFD_SETLK" : NO 
Checking for function "pwrite" : YES 
Run-time dependency efiboot found: YES 37
Run-time dependency efivar found: YES 37
Header <efivar/efivar-types.h> has symbol "efi_time_t" with dependency efivar: NO 
Run-time dependency umockdev-1.0 found: YES 0.17.12
Run-time dependency flashrom found: YES unknown
Run-time dependency systemd found: YES 250
Dependency systemd found: YES 250 (cached)
Configuring config.h using configuration
Run-time dependency libprotobuf-c found: YES 1.4.0
Program protoc found: YES (/usr/bin/protoc)

meson.build:542:4: ERROR: Problem encountered: 

A full log can be found at /usr/src/fwupd-1.8.1/build/meson-logs/meson-log.txt

**Comment by stumbles** [comment]
Is this still an issue?

**Comment by lhw828** [comment]
Still the error message.

**Comment by lhw828** [comment]
> Is this still an issue?

Library m found: YES
Run-time dependency libgcab-1.0 found: YES 1.4
Checking for function "gcab_file_set_bytes" with dependency libgcab-1.0: NO 
Run-time dependency bash-completion found: YES 2.11
Program python3 found: YES (/usr/bin/python3)
Run-time dependency gnutls found: YES 3.7.6
Run-time dependency liblzma found: YES 5.2.5
Dependency libcbor skipped: feature cbor disabled
Run-time dependency libsystemd found: YES 250
Has header "sys/utsname.h" : YES 
Has header "sys/inotify.h" : YES 
Has header "sys/ioctl.h" : YES 
Has header "errno.h" : YES 
Has header "sys/socket.h" : YES 
Has header "sys/io.h" : YES 
Checking for function "outb" : YES 
Has header "linux/ethtool.h" : YES 
Has header "mtd/mtd-user.h" : YES 
Has header "linux/hidraw.h" : YES 
Has header "sys/mman.h" : YES 
Has header "poll.h" : YES 
Has header "fnmatch.h" : YES 
Has header "kenv.h" : NO 
Has header "malloc.h" : YES 
Checking for function "malloc_trim" : YES 
Header <cpuid.h> has symbol "__get_cpuid_count" : YES 
Checking for function "getuid" : YES 
Checking for function "realpath" : YES 
Checking for function "memmem" : YES 
Checking for function "sigaction" : YES 
Checking for function "memfd_create" : YES 
Header <locale.h> has symbol "LC_MESSAGES" : YES 
Has header "linux/ipmi.h" : YES 
Header <fcntl.h> has symbol "F_WRLCK" : YES 
Header <fcntl.h> has symbol "F_OFD_SETLK" : NO 
Checking for function "pwrite" : YES 
Run-time dependency efiboot found: YES 37
Run-time dependency efivar found: YES 37
Header <efivar/efivar-types.h> has symbol "efi_time_t" with dependency efivar: NO 

meson.build:439:6: ERROR: Problem encountered: Error: missing dependency python gobject introspection (python3-gi)

**Comment by stumbles** [comment]
Missing gobject-introspection. You might want to lunar fix python and say no when it wants to rebuild any python3 modules.
