### ISSUE TITLE
ruby:something wrong with CFLAGS="  -O2 -march=x86-64 -pipe -Wp,-D_FORTIFY_SOURCE=2  "

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-other#1868]
checking for minix/config.h... no
checking whether it is safe to define __EXTENSIONS__... yes
checking whether the linker is GNU ld... yes
checking whether cpp accepts -o... yes
checking for gcc... /var/lib/lunar/compilers/gcc
checking for gcc-ar flags... rcD
checking whether ln -s works... yes
checking whether make sets $(MAKE)... yes
checking for a BSD-compatible install... /usr/bin/install -c
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for dtrace... no
checking for dot... dot
checking for doxygen... doxygen
checking for pkg-config... pkg-config
checking whether it is Android... no
checking for cd using physical directory... cd -P
checking whether CFLAGS is valid... no
configure: error: something wrong with CFLAGS="  -O2 -march=x86-64 -pipe -Wp,-D_FORTIFY_SOURCE=2  "
Creating /var/log/lunar/compile/ruby-3.1.2.xz

**Comment by Ratler** [comment]
Could you attach the config.log from ruby please, should be in the /usr/src/ruby... directory. Thanks!

**Comment by lhw828** [comment]
[Uploading config.log…]()
