### ISSUE TITLE
circular dependencies in python part

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-other#2221]
Checking dependencies for python-pyopenssl 
Checking dependencies for python-pytest 
Checking dependencies for python-py 
Checking dependencies for python-setuptools-scm 
Checking dependencies for python-apipkg 
Checking dependencies for python-hatchling 
Checking dependencies for python-hatch-vcs 
Checking dependencies for python-iniconfig 
Checking dependencies for python-pluggy 
Checking dependencies for python-importlib-metadata 
Checking dependencies for python-pep517 
Checking dependencies for python-pytest 
Checking dependencies for python-pluggy 
Checking dependencies for python-importlib-metadata 
Checking dependencies for python-pep517 
Checking dependencies for python-pytest 
Checking dependencies for python-pluggy 
Checking dependencies for python-importlib-metadata 

circular circular circular circular

**Comment by stumbles** [comment]
Made some changes.  Give it another go.

**Comment by lhw828** [comment]
> Made some changes. Give it another go.

https://github.com/lunar-linux/moonbase-other/pull/2226

It seems that the problem still exists.

The CI showout:

the_silver_searcher: other/crater -> other/utils
  xbase: other/sql -> other/crater
  xf86-video-modesetting: xorg/crater -> xorg/driver
  yasm: core/compilers -> other/compilers
  zstd: other/archive -> core/archive

/bin/bash: warning: shell level (1000) too high, resetting to 1

**Comment by stumbles** [comment]
Unless there's a real need for the 3 modules in crater, you should avoid them.

As for yasm only depends on python.

zstd does not depend on python
