### ISSUE TITLE
lld:CMake Error at cmake/modules/AddLLD.cmake:63

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-other#2243]
-- Performing Test C_SUPPORTS_FFUNCTION_SECTIONS - Success
-- Performing Test CXX_SUPPORTS_FFUNCTION_SECTIONS
-- Performing Test CXX_SUPPORTS_FFUNCTION_SECTIONS - Success
-- Performing Test C_SUPPORTS_FDATA_SECTIONS
-- Performing Test C_SUPPORTS_FDATA_SECTIONS - Success
-- Performing Test CXX_SUPPORTS_FDATA_SECTIONS
-- Performing Test CXX_SUPPORTS_FDATA_SECTIONS - Success
-- Looking for os_signpost_interval_begin
-- Looking for os_signpost_interval_begin - not found
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS_WITHOUT_LIB - Success
-- Performing Test HAVE_CXX_ATOMICS64_WITHOUT_LIB
-- Performing Test HAVE_CXX_ATOMICS64_WITHOUT_LIB - Success
-- Performing Test LLVM_HAS_ATOMICS
-- Performing Test LLVM_HAS_ATOMICS - Success
-- Found Python3: /usr/bin/python3.10 (found suitable version "3.10.7", minimum required is "3.6") found components: Interpreter 
-- LLD version: 14.0.6
-- Found Git: /usr/bin/git (found version "2.39.1") 
CMake Error at cmake/modules/AddLLD.cmake:63 (llvm_add_tool_symlink):
  Unknown CMake command "llvm_add_tool_symlink".
Call Stack (most recent call first):
  tools/lld/CMakeLists.txt:31 (add_lld_symlink)

-- Configuring incomplete, errors occurred!
See also "/usr/src/lld-15.0.7/lld-15.0.7.src/build/CMakeFiles/CMakeOutput.log".
See also "/usr/src/lld-15.0.7/lld-15.0.7.src/build/CMakeFiles/CMakeError.log".
Creating /var/log/lunar/compile/lld-15.0.7.xz 
! Problem detected during BUILD

**Comment by stumbles** [comment]
Closed by commit 1f43fc12d8cfea54c2a5a70d31bf350155285712.
