### ISSUE TITLE
mesa-lib:Program 'glslangValidator' not found or not executable

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-other#2246]
Checking dependencies for mesa-lib 
Building mesa-lib version 22.3.2
The Meson build system
Version: 0.63.2
Source dir: /usr/src/mesa-22.3.2
Build dir: /usr/src/mesa-22.3.2/build
Build type: native build
Program python3 found: YES (/usr/bin/python3)
Project name: mesa
Project version: 22.3.2
C compiler for the host machine: gcc (gcc 12.1.1 "gcc (GCC) 12.1.1 20220730")
C linker for the host machine: gcc ld.bfd 2.39
C++ compiler for the host machine: g++ (gcc 12.1.1 "g++ (GCC) 12.1.1 20220730")
C++ linker for the host machine: g++ ld.bfd 2.39
Host machine cpu family: x86_64
Host machine cpu: x86_64
Checking if "-mtls-dialect=gnu2" runs: YES
Checking if "split TLSDESC" : links: YES 
Found pkg-config: /usr/bin/pkg-config (1.9.3)
Run-time dependency vdpau found: YES 1.5
Program glslangValidator found: NO

meson.build:697:2: ERROR: Program 'glslangValidator' not found or not executable

**Comment by stumbles** [comment]
fix your glslang.
