### ISSUE TITLE
gobject-introspection:need glib-2.0 >=2.75.0

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-other#2262]
Compiler for C supports arguments -Wundef: YES 
Compiler for C supports arguments -Wunused-but-set-variable: YES 
Compiler for C supports arguments -Wwrite-strings: YES 
Compiler for C supports arguments -fno-strict-aliasing: YES 
Checking for size of "char" : 1
Checking for size of "short" : 2
Checking for size of "int" : 4
Checking for size of "long" : 8
Found pkg-config: /usr/bin/pkg-config (1.9.3)
Dependency glib-2.0 found: NO found 2.72.2 but need: '>=2.75.0'
Found CMake: /usr/bin/cmake (3.25.2)
Run-time dependency glib-2.0 found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency glib-2.0

meson.build:130:0: ERROR: Git command failed: ['/usr/bin/git', '-c', 'advice.detachedHead=false', 'clone', '--depth', '1', '--branch', 'main', 'https://gitlab.gnome.org/GNOME/glib.git', 'glib']

A full log can be found at /usr/src/gobject-introspection-1.75.6/build/meson-logs/meson-log.txt
Creating /var/log/lunar/compile/gobject-introspection-1.75.6.xz

**Comment by stumbles** [comment]
So locally bump your glib-2, do a lunar hold glib-2 (till it gets merged), and recompile gobject-introspection.

**Comment by stumbles** [comment]
Closing with https://github.com/lunar-linux/moonbase-core/commit/83ece299db588acc2ba025edc061f2d76273d793

Update your moonbase.
