### ISSUE TITLE
msgpack-c:looks like need gtest

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-other#2369]
Checking dependencies for msgpack-c 
Building msgpack-c version 6.0.0
-- The C compiler identification is GNU 12.1.1
-- The CXX compiler identification is GNU 12.1.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /var/lib/lunar/compilers/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /var/lib/lunar/compilers/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR
  GTEST_MAIN_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-3.26/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.26/Modules/FindGTest.cmake:270 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  test/CMakeLists.txt:1 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!

**Comment by stumbles** [comment]
This was fixed with commit ad7fdba11ea011c1d925b3289cf4af2c66a352e18d4c7264392fead75e919363
