### ISSUE TITLE
spirv-llvm-translator:make: *** [Makefile:136: all] Error 2

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-other#3378]
Building spirv-llvm-translator version 17.0.0
patching file include/LLVMSPIRVExtensions.inc
patching file lib/SPIRV/SPIRVWriter.cpp
patching file lib/SPIRV/libSPIRV/SPIRVEntry.h
patching file lib/SPIRV/libSPIRV/SPIRVModule.cpp
patching file lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h
patching file test/SpecConstants/long-spec-const-composite.ll
patching file test/long-constant-array.ll
patching file test/long-type-struct.ll
-- Found PkgConfig: /usr/bin/pkg-config (found version "2.1.0") 
-- Using SPIR-V Headers from
          /usr/include/spirv/
-- The CXX compiler identification is Clang 17.0.6
-- The C compiler identification is Clang 17.0.6
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test HAVE_FFI_CALL
-- Performing Test HAVE_FFI_CALL - Success
-- Found FFI: /usr/lib/libffi.so  
-- Performing Test Terminfo_LINKABLE
-- Performing Test Terminfo_LINKABLE - Success
-- Found Terminfo: /lib/libcurses.so  
-- Found ZLIB: /lib/libz.so (found version "1.3")  
-- Found zstd: /usr/lib/libzstd.so  
-- Found LibXml2: /usr/lib/libxml2.so (found version "2.12.4") 
-- Linker detection: GNU ld
-- Performing Test LLVM_LIBSTDCXX_MIN
-- Performing Test LLVM_LIBSTDCXX_MIN - Success
-- Performing Test LLVM_LIBSTDCXX_SOFT_ERROR
-- Performing Test LLVM_LIBSTDCXX_SOFT_ERROR - Success
-- Performing Test C_SUPPORTS_FPIC
-- Performing Test C_SUPPORTS_FPIC - Success
-- Performing Test CXX_SUPPORTS_FPIC
-- Performing Test CXX_SUPPORTS_FPIC - Success
-- Building with -fPIC
-- Performing Test C_SUPPORTS_FNO_SEMANTIC_INTERPOSITION
-- Performing Test C_SUPPORTS_FNO_SEMANTIC_INTERPOSITION - Success
-- Performing Test CXX_SUPPORTS_FNO_SEMANTIC_INTERPOSITION
-- Performing Test CXX_SUPPORTS_FNO_SEMANTIC_INTERPOSITION - Success
-- Performing Test SUPPORTS_FVISIBILITY_INLINES_HIDDEN_FLAG
-- Performing Test SUPPORTS_FVISIBILITY_INLINES_HIDDEN_FLAG - Success
-- Performing Test C_SUPPORTS_WERROR_DATE_TIME
-- Performing Test C_SUPPORTS_WERROR_DATE_TIME - Success
-- Performing Test CXX_SUPPORTS_WERROR_DATE_TIME
-- Performing Test CXX_SUPPORTS_WERROR_DATE_TIME - Success
-- Performing Test C_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW
-- Performing Test C_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW - Success
-- Performing Test CXX_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW
-- Performing Test CXX_SUPPORTS_WERROR_UNGUARDED_AVAILABILITY_NEW - Success
-- Performing Test C_SUPPORTS_CMAKE_CXX_FLAGS
-- Performing Test C_SUPPORTS_CMAKE_CXX_FLAGS - Failed
-- Performing Test CXX_SUPPORTS_CMAKE_CXX_FLAGS
-- Performing Test CXX_SUPPORTS_CMAKE_CXX_FLAGS - Failed
-- Performing Test CXX_SUPPORTS_MISSING_FIELD_INITIALIZERS_FLAG
-- Performing Test CXX_SUPPORTS_MISSING_FIELD_INITIALIZERS_FLAG - Success
-- Performing Test C_SUPPORTS_IMPLICIT_FALLTHROUGH_FLAG
-- Performing Test C_SUPPORTS_IMPLICIT_FALLTHROUGH_FLAG - Success
-- Performing Test CXX_SUPPORTS_IMPLICIT_FALLTHROUGH_FLAG
-- Performing Test CXX_SUPPORTS_IMPLICIT_FALLTHROUGH_FLAG - Success
-- Performing Test C_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG
-- Performing Test C_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG - Success
-- Performing Test CXX_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG
-- Performing Test CXX_SUPPORTS_COVERED_SWITCH_DEFAULT_FLAG - Success
-- Performing Test CXX_SUPPORTS_CLASS_MEMACCESS_FLAG
-- Performing Test CXX_SUPPORTS_CLASS_MEMACCESS_FLAG - Failed
-- Performing Test CXX_SUPPORTS_NOEXCEPT_TYPE_FLAG
-- Performing Test CXX_SUPPORTS_NOEXCEPT_TYPE_FLAG - Success
-- Performing Test CXX_WONT_WARN_ON_FINAL_NONVIRTUALDTOR
-- Performing Test CXX_WONT_WARN_ON_FINAL_NONVIRTUALDTOR - Success
-- Performing Test CXX_SUPPORTS_SUGGEST_OVERRIDE_FLAG
-- Performing Test CXX_SUPPORTS_SUGGEST_OVERRIDE_FLAG - Success
-- Performing Test CXX_WSUGGEST_OVERRIDE_ALLOWS_ONLY_FINAL
-- Performing Test CXX_WSUGGEST_OVERRIDE_ALLOWS_ONLY_FINAL - Success
-- Performing Test C_WCOMMENT_ALLOWS_LINE_WRAP
-- Performing Test C_WCOMMENT_ALLOWS_LINE_WRAP - Success
-- Performing Test C_SUPPORTS_STRING_CONVERSION_FLAG
-- Performing Test C_SUPPORTS_STRING_CONVERSION_FLAG - Success
-- Performing Test CXX_SUPPORTS_STRING_CONVERSION_FLAG
-- Performing Test CXX_SUPPORTS_STRING_CONVERSION_FLAG - Success
-- Performing Test C_SUPPORTS_MISLEADING_INDENTATION_FLAG
-- Performing Test C_SUPPORTS_MISLEADING_INDENTATION_FLAG - Success
-- Performing Test CXX_SUPPORTS_MISLEADING_INDENTATION_FLAG
-- Performing Test CXX_SUPPORTS_MISLEADING_INDENTATION_FLAG - Success
-- Performing Test C_SUPPORTS_CTAD_MAYBE_UNSPPORTED_FLAG
-- Performing Test C_SUPPORTS_CTAD_MAYBE_UNSPPORTED_FLAG - Success
-- Performing Test CXX_SUPPORTS_CTAD_MAYBE_UNSPPORTED_FLAG
-- Performing Test CXX_SUPPORTS_CTAD_MAYBE_UNSPPORTED_FLAG - Success
-- Performing Test C_SUPPORTS_FNO_FUNCTION_SECTIONS
-- Performing Test C_SUPPORTS_FNO_FUNCTION_SECTIONS - Success
-- Performing Test C_SUPPORTS_FFUNCTION_SECTIONS
-- Performing Test C_SUPPORTS_FFUNCTION_SECTIONS - Success
-- Performing Test CXX_SUPPORTS_FFUNCTION_SECTIONS
-- Performing Test CXX_SUPPORTS_FFUNCTION_SECTIONS - Success
-- Performing Test C_SUPPORTS_FDATA_SECTIONS
-- Performing Test C_SUPPORTS_FDATA_SECTIONS - Success
-- Performing Test CXX_SUPPORTS_FDATA_SECTIONS
-- Performing Test CXX_SUPPORTS_FDATA_SECTIONS - Success
-- Looking for os_signpost_interval_begin
-- Looking for os_signpost_interval_begin - not found
-- Found LLVM: 17.0.6
-- Found ccache: /usr/bin/ccache
-- Checking for one of the modules 'SPIRV-Tools'
-- Configuring done (11.4s)
-- Generating done (0.0s)
-- Build files have been written to: /usr/src/SPIRV-LLVM-Translator-17.0.0/spirv-llvm-translator-17.0.0
make: Entering directory '/usr/src/SPIRV-LLVM-Translator-17.0.0/spirv-llvm-translator-17.0.0'
[  0%] Built target intrinsics_gen
[  4%] Building CXX object lib/SPIRV/CMakeFiles/LLVMSPIRVLib.dir/LLVMToSPIRVDbgTran.cpp.o
[  4%] Building CXX object lib/SPIRV/CMakeFiles/LLVMSPIRVLib.dir/LLVMSPIRVOpts.cpp.o
[  7%] Building CXX object lib/SPIRV/CMakeFiles/LLVMSPIRVLib.dir/Mangler/FunctionDescriptor.cpp.o
[  9%] Building CXX object lib/SPIRV/CMakeFiles/LLVMSPIRVLib.dir/Mangler/Mangler.cpp.o
[ 12%] Building CXX object lib/SPIRV/CMakeFiles/LLVMSPIRVLib.dir/Mangler/ManglingUtils.cpp.o
[ 14%] Building CXX object lib/SPIRV/CMakeFiles/LLVMSPIRVLib.dir/Mangler/ParameterType.cpp.o
[ 17%] Building CXX object lib/SPIRV/CMakeFiles/LLVMSPIRVLib.dir/OCLToSPIRV.cpp.o
In file included from /usr/src/SPIRV-LLVM-Translator-17.0.0/lib/SPIRV/LLVMToSPIRVDbgTran.cpp:38:
In file included from /usr/src/SPIRV-LLVM-Translator-17.0.0/lib/SPIRV/LLVMToSPIRVDbgTran.h:42:
In file included from /usr/src/SPIRV-LLVM-Translator-17.0.0/lib/SPIRV/libSPIRV/SPIRVModule.h:44:
/usr/src/SPIRV-LLVM-Translator-17.0.0/lib/SPIRV/libSPIRV/SPIRVEntry.h:911:19: error: use of undeclared identifier 'CapabilityLongCompositesINTEL'; did you mean 'spv::internal::CapabilityFastCompositeINTEL'?
  911 |     return getVec(CapabilityLongCompositesINTEL);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                   spv::internal::CapabilityFastCompositeINTEL
/usr/src/SPIRV-LLVM-Translator-17.0.0/lib/SPIRV/libSPIRV/spirv_internal.hpp:261:22: note: 'spv::internal::CapabilityFastCompositeINTEL' declared here
  261 | constexpr Capability CapabilityFastCompositeINTEL =
      |                      ^
In file included from /usr/src/SPIRV-LLVM-Translator-17.0.0/lib/SPIRV/LLVMToSPIRVDbgTran.cpp:39:
In file included from /usr/src/SPIRV-LLVM-Translator-17.0.0/lib/SPIRV/SPIRVWriter.h:47:
In file included from /usr/src/SPIRV-LLVM-Translator-17.0.0/lib/SPIRV/OCLUtil.h:42:
In file included from /usr/src/SPIRV-LLVM-Translator-17.0.0/lib/SPIRV/SPIRVInternal.h:45:
/usr/src/SPIRV-LLVM-Translator-17.0.0/lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h:613:7: error: use of undeclared identifier 'CapabilityLongCompositesINTEL'; did you mean 'spv::internal::CapabilityFastCompositeINTEL'?
  613 |   add(CapabilityLongCompositesINTEL, "LongCompositesINTEL");
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       spv::internal::CapabilityFastCompositeINTEL
/usr/src/SPIRV-LLVM-Translator-17.0.0/lib/SPIRV/libSPIRV/spirv_internal.hpp:261:22: note: 'spv::internal::CapabilityFastCompositeINTEL' declared here
  261 | constexpr Capability CapabilityFastCompositeINTEL =
      |                      ^
2 errors generated.
make[2]: *** [lib/SPIRV/CMakeFiles/LLVMSPIRVLib.dir/build.make:90: lib/SPIRV/CMakeFiles/LLVMSPIRVLib.dir/LLVMToSPIRVDbgTran.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /usr/src/SPIRV-LLVM-Translator-17.0.0/lib/SPIRV/OCLToSPIRV.cpp:41:
In file included from /usr/src/SPIRV-LLVM-Translator-17.0.0/lib/SPIRV/OCLToSPIRV.h:43:
In file included from /usr/src/SPIRV-LLVM-Translator-17.0.0/lib/SPIRV/OCLUtil.h:42:
In file included from /usr/src/SPIRV-LLVM-Translator-17.0.0/lib/SPIRV/SPIRVInternal.h:45:
/usr/src/SPIRV-LLVM-Translator-17.0.0/lib/SPIRV/libSPIRV/SPIRVNameMapEnum.h:613:7: error: use of undeclared identifier 'CapabilityLongCompositesINTEL'; did you mean 'spv::internal::CapabilityFastCompositeINTEL'?
  613 |   add(CapabilityLongCompositesINTEL, "LongCompositesINTEL");
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |       spv::internal::CapabilityFastCompositeINTEL
/usr/src/SPIRV-LLVM-Translator-17.0.0/lib/SPIRV/libSPIRV/spirv_internal.hpp:261:22: note: 'spv::internal::CapabilityFastCompositeINTEL' declared here
  261 | constexpr Capability CapabilityFastCompositeINTEL =
      |                      ^
In file included from /usr/src/SPIRV-LLVM-Translator-17.0.0/lib/SPIRV/OCLToSPIRV.cpp:41:
In file included from /usr/src/SPIRV-LLVM-Translator-17.0.0/lib/SPIRV/OCLToSPIRV.h:43:
In file included from /usr/src/SPIRV-LLVM-Translator-17.0.0/lib/SPIRV/OCLUtil.h:42:
In file included from /usr/src/SPIRV-LLVM-Translator-17.0.0/lib/SPIRV/SPIRVInternal.h:46:
In file included from /usr/src/SPIRV-LLVM-Translator-17.0.0/lib/SPIRV/libSPIRV/SPIRVType.h:47:
/usr/src/SPIRV-LLVM-Translator-17.0.0/lib/SPIRV/libSPIRV/SPIRVEntry.h:911:19: error: use of undeclared identifier 'CapabilityLongCompositesINTEL'; did you mean 'spv::internal::CapabilityFastCompositeINTEL'?
  911 |     return getVec(CapabilityLongCompositesINTEL);
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                   spv::internal::CapabilityFastCompositeINTEL
/usr/src/SPIRV-LLVM-Translator-17.0.0/lib/SPIRV/libSPIRV/spirv_internal.hpp:261:22: note: 'spv::internal::CapabilityFastCompositeINTEL' declared here
  261 | constexpr Capability CapabilityFastCompositeINTEL =
      |                      ^
2 errors generated.
make[2]: *** [lib/SPIRV/CMakeFiles/LLVMSPIRVLib.dir/build.make:160: lib/SPIRV/CMakeFiles/LLVMSPIRVLib.dir/OCLToSPIRV.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:247: lib/SPIRV/CMakeFiles/LLVMSPIRVLib.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
make: Leaving directory '/usr/src/SPIRV-LLVM-Translator-17.0.0/spirv-llvm-translator-17.0.0'

**Comment by stumbles** [comment]
Compiles fine here.

Side note; from cli doing;

PSAFE=no lin -c spirv-llvm-translator

will give a better view of what actually went wrong, as indicated by "make[2]: *** Waiting for unfinished jobs...." .
