### ISSUE TITLE
cups-filters: cupsfilters/driver.h: No such file or directory

### ISSUE THREAD

**Issue by lhw828** [lunar-linux/moonbase-other#4208]
make[1]: Entering directory '/usr/src/cups-filters-2.0.1'
  CC       filter/pdftopdf-pdftopdf.o
  CC       filter/texttotext-texttotext.o
  CC       filter/rastertoescpx-rastertoescpx.o
  CC       filter/rastertopclx-pcl-common.o
  CC       filter/rastertopclx-rastertopclx.o
filter/rastertoescpx.c:28:10: fatal error: cupsfilters/driver.h: No such file or directory
   28 | #include <cupsfilters/driver.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:2351: filter/rastertoescpx-rastertoescpx.o] Error 1
make[1]: *** Waiting for unfinished jobs....
filter/pcl-common.c:21:10: fatal error: cupsfilters/driver.h: No such file or directory
   21 | #include <cupsfilters/driver.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:2365: filter/rastertopclx-pcl-common.o] Error 1
In file included from filter/pcl-common.h:15,
                 from filter/rastertopclx.c:27:
/usr/include/ppd/ppd.h:27:12: fatal error: cupsfilters/driver.h: No such file or directory
   27 | #  include <cupsfilters/driver.h>
      |            ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:2379: filter/rastertopclx-rastertopclx.o] Error 1
In file included from /usr/include/ppd/ppd-filter.h:39,
                 from filter/texttotext.c:15:
/usr/include/ppd/ppd.h:27:12: fatal error: cupsfilters/driver.h: No such file or directory
   27 | #  include <cupsfilters/driver.h>
      |            ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:2463: filter/texttotext-texttotext.o] Error 1
In file included from /usr/include/ppd/ppd-filter.h:39,
                 from filter/pdftopdf.c:15:
/usr/include/ppd/ppd.h:27:12: fatal error: cupsfilters/driver.h: No such file or directory
   27 | #  include <cupsfilters/driver.h>
      |            ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[1]: *** [Makefile:2253: filter/pdftopdf-pdftopdf.o] Error 1
make[1]: Leaving directory '/usr/src/cups-filters-2.0.1'
make: *** [Makefile:2654: install-recursive] Error 1

**Comment by esselfe** [comment]
This was fixed with the addition of the libcupsfilters module, see https://github.com/lunar-linux/moonbase-other/pull/4188
