### ISSUE TITLE
Bump eclipse-bin to Mars

### ISSUE THREAD

**Issue by WillPittenger** [lunar-linux/moonbase-other#602]
The Eclipse developers have released Mars 4.5.  I think we should update to that version.

**Comment by v4hn** [comment]
Sorry for never replying to this...

Our eclipse-bin module is years old.
Sure, we could upgrade it and pull-requests are welcome.
It's just one of these beasts nobody wants to touch unless they use it themselves and as Eclipse provides user-space installers anyway it is not urgent either.

Closing. Feel free to add a working pull-request though! :)
