### ISSUE TITLE
OpenVPN systemd unit has wrong path?

### ISSUE THREAD

**Issue by awh-tokyo** [lunar-linux/moonbase-other#628]
The OpenVPN systemd unit runs /usr/bin/openvpn, but on my system, openvpn installed into /usr/sbin.

I don't know if it's installed into a nonstandard location on mine, so I thought I'd point it out so the maintainer can see if this is a problem for everyone or just me.

**Comment by Florin65** [comment]
You're right. I fixed that. Thank you.
