### ISSUE TITLE
WARNING: BUILD does not call prepare_install or installs zero files!

### ISSUE THREAD

**Issue by mwgrient** [lunar-linux/moonbase-other#737]
CXXLD    urftopdf
  CXXLD    rastertopdf
  CCLD     rastertops
  CXXLD    bannertopdf
  CXXLD    pdftoraster
  CXXLD    pdftoijs
  CCLD     gstoraster
  CCLD     foomatic-rip
  CCLD     cups-browsed
pdftoraster-pdftoraster.o: In function `main':
pdftoraster.cxx:(.text.startup+0x1e3f): undefined reference to `GfxColorSpace::setDisplayProfile(void*)'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:2298: pdftoraster] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/usr/src/cups-filters-1.11.6'
make: *** [Makefile:1865: all] Error 2
WARNING: BUILD does not call prepare_install or installs zero files!
Creating /var/log/lunar/compile/cups-filters-1.11.6.xz 
Creating /var/log/lunar/install/cups-filters-1.11.6
Creating /var/log/lunar/md5sum/cups-filters-1.11.6
Creating /var/cache/lunar/cups-filters-1.11.6-x86_64-pc-linux-gnu.tar.xz

If needed I can provide extra info. But I do not have a clue what is going on.
Regards, marco

**Comment by v4hn** [comment]
I can't reproduce this over here, build succeeds on my system.
However, I just added a missing && and now your build should not "succeed" despite the error anymore.

**Comment by mwgrient** [comment]
Pitty! And thanks for the &&.

**Comment by v4hn** [comment]
the missing function is provided by `/usr/lib/libpoppler.so` from the `poppler` module over here.
Maybe rebuild that one?

**Comment by mwgrient** [comment]
I have doe that just a second ago. Thank you for your time. But the cups-filter module is still not building, and spits out the same error.

**Comment by mwgrient** [comment]
I did a rebuild of all the packages needed for printing and now it does work! SOLVED!
