### ISSUE TITLE
lin pepperflash -w 22.0.0.209 to omit key check, gives no such file in /opt

### ISSUE THREAD

**Issue by mwgrient** [lunar-linux/moonbase-other#750]
root@tulp ~ # `lin pepperflash -w 22.0.0.209`
Checking dependencies for pepperflash 
Building pepperflash version 22.0.0.209
WARNING: Integrity checking is disabled when using "--want"!
`install: cannot stat 'opt/google/chrome/PepperFlash/*': No such file or directory`
Creating /var/log/lunar/compile/pepperflash-22.0.0.209.bz2 
! Problem detected during BUILD

I have created the directories by hand. But the error persist.
Regards Marco

**Comment by v4hn** [comment]
iirc @stumbles was interested in this module and created it.

It looks like the chromium deb packages one can download upstream does not provide pepperflash anymore. Any idea where to get it now?

**Comment by mwgrient** [comment]
[adobe pepperflash link](https://get.adobe.com/nl/flashplayer/?no_redirect)

The above link, looks like libpepflashplayer.so, manifest.json and a README, which contains:

> Adobe Systems Incorporated
> Flash Player for Linux
> 23.0.0.207
> 
> Adobe recommends that all users upgrade to the latest version of Adobe Flash
> Player for the most recent features, bug fixes, and security fixes.  For
> more information on the new features in Flash Player, please visit
> http://www.adobe.com/products/flashplayer/.  For more information on system
> requirements, fixed issues, and known issues, see the release notes at
> http://www.adobe.com/go/flashplayer_releasenotes.
> 
> To confirm which version of Flash Player you have currently installed, see
> http://www.adobe.com/software/flash/about/. Users should only install
> Players that have been downloaded from trusted sources, such as
> http://www.adobe.com/.
> 
> Your use of this player is governed by the Adobe End User License Agreement
> found at http://www.adobe.com/products/eulas/players/flash/.
>

**Comment by v4hn** [comment]
Thanks for the pointer, with firefox that site still shows the old 11 version by default.
I fixed the module in 4cc360fcfa040726bbdc039e2c51b1087a62f97e and flash PPAPI works for me in firefox with that module.

Thank you, you just made me waste half an hour of my life "testing" whether flash works correctly :P
