### ISSUE TITLE
libreoffice missing cairo-pdf.h from cairo on jenkins

### ISSUE THREAD

**Issue by ghost** [lunar-linux/moonbase-other#805]
libreoffice compilation fails due to a missing /usr/include/cairo/cairo-pdf.h, which is from cairo compiled with poppler for PDF support. This is enabled using --enable-pdf=[no/auto/yes] from cairo's './configure --help', but running the configure says it's --[enable/disable]... 
So I tried both "depends" and "optional_depends" for poppler in cairo's DEPENDS, but when merged, jenkins still configures it without PDF support...

**Comment by Florin65** [comment]
We don't have a libreoffice module now. There is only the libreoffice-bin module.
